services:
  web:
    build:
      context: ./web
      args:
        PORT: 8000
    ports:
      - 8000:8000
    env_file:
      - ./db.env
    depends_on:
      - auth
      - catalog
      - cart
      - payment
      - order
    volumes:
      - ./web:/app
    networks:
      - backend
  auth:
    build:
      context: ./auth
      args:
        PORT: 8001
    ports:
      - 8001:8001
    env_file:
      - ./db.env
      - ./auth.env
    depends_on:
      - db
    volumes:
      - ./auth:/app
    networks:
      - backend
  catalog:
    build:
      context: ./catalog
      args:
        PORT: 8002
    ports:
      - 8002:8002
    env_file:
      - ./db.env
    depends_on:
      - db
    volumes:
      - ./catalog:/app
    networks:
      - backend
  cart:
    build: ./cart
    ports:
      - 8003:8003
    depends_on:
      - db
    volumes:
      - ./cart:/app
  payment:
    build: ./payment
    ports:
      - 8004:8004
    depends_on:
      - db
    volumes:
      - ./payment:/app
  order:
    build: ./order
    ports:
      - 8005:8005
    depends_on:
      - db
    volumes:
      - ./order:/app
  notification:
    build: ./notification
    ports:
      - 8006:8006
    depends_on:
      - db
    volumes:
      - ./notification:/app
  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    env_file:
      - ./db.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      backend:
        ipv4_address: 10.5.0.10

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
